### ISSUE TITLE
Have you found fix for this issue?

### ISSUE THREAD

**Issue by henrykaasik** [leedavidcs/nextjs-react-jss-warning#4]
Hei!

I found your code. I have exactly the same problem. 
Have you found some fix for this issue? Or how to overcome this?

Best Regards
Henry

**Comment by i3dly** [comment]
Sadly, I haven't.

If you want to continue using dynamic styles without jss logging errors, I think you'd need to wait for a fix by the jss maintainers.

I worked around the problem by converting my classes that used dynamic styles into multiple classes that I toggled between using the classnames module.

Obviously, this isn't the greatest solution if you need to do some computations based on props. In this case, you'll need to use the style property on elements (which isn't great), or you'll need to just ignore the errors that jss logs out.

Sorry 8(

**Comment by henrykaasik** [comment]
Thx for your fast response 👍 :)
I think i just currently ignore the warnings and wait for the fix.
